[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "tmux-256color"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001bb"  # Alt+b for backward-word

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001bf"  # Alt+f for forward-word

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001\u0001"  # Ctrl+A for beginning of line

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"  # Ctrl+E for end of line

[window]
padding.x = 10
padding.y = 30

decorations = "Transparent"

opacity = 0.9
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 14.0

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" }
]
