# Set prefix key to Ctrl+a (optional, default is Ctrl+b)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Command history navigation
bind -n C-p command-prompt -p "previous command:" "send-keys -R \; send-keys Up"
bind -n C-n command-prompt -p "next command:" "send-keys -R \; send-keys Down"

# Word navigation bindings
bind-key -n C-Left send-keys M-b
bind-key -n C-Right send-keys M-f

# Line navigation bindings
bind-key -n M-Left send-keys C-a
bind-key -n M-Right send-keys C-e

# Shell settings
set -g default-shell /bin/bash
set -g default-command "bash -l"
set -sg escape-time 50
set -g base-index 1
set -g pane-base-index 1

# Status line at the top
set-option -g status-position top

set -g status 2
set -g status-format[1] ''

# Create Panes: window splitting
## Split vertically
unbind %
bind | split-window -h -c "#{pane_current_path}" # Prefix | to create vertical split

## Split horizontally
unbind '"'
bind - split-window -v -c "#{pane_current_path}" # Prefix - to create horizontal split

set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"

# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Reload config easily
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Catppuccin theme
set -g @plugin 'catppuccin/tmux'

# Initialize TPM (Tmux Plugin Manager)
run '~/.tmux/plugins/tpm/tpm'
